# Generated by Django 4.1.6 on 2023-02-21 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='店名')),
                ('image', models.ImageField(upload_to='ShopImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(verbose_name='支払い金額')),
                ('is_paid', models.BooleanField(default=False, verbose_name='支払い状況')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 2, 21, 14, 21, 29, 523280), verbose_name='決済日時')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shops')),
            ],
        ),
    ]
