# Generated by Django 4.1.6 on 2023-02-22 03:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': '決済記録', 'verbose_name_plural': '決済記録'},
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': '登録店', 'verbose_name_plural': '登録店'},
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 12, 28, 40, 455958), verbose_name='決済日時'),
        ),
        migrations.CreateModel(
            name='Reviewes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='タイトル')),
                ('message', models.CharField(max_length=2048, verbose_name='本文')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '口コミ',
                'verbose_name_plural': '口コミ',
            },
        ),
    ]
