# Generated by Django 4.1.6 on 2023-02-22 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_payments_options_alter_shops_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewes',
            name='user',
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 12, 38, 56, 825273), verbose_name='決済日時'),
        ),
    ]
